// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrEyepVi0ocK769ME74RNbBvVys-RITkk',
    appId: '1:805932440174:web:123fc01f79865fe4f6e47f',
    messagingSenderId: '805932440174',
    projectId: 'inpatient-transport',
    authDomain: 'inpatient-transport.firebaseapp.com',
    storageBucket: 'inpatient-transport.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gjwVarsliKyFbtxuldSHK3FpcCTwkmE',
    appId: '1:805932440174:android:261b1c2a30e5ad6bf6e47f',
    messagingSenderId: '805932440174',
    projectId: 'inpatient-transport',
    storageBucket: 'inpatient-transport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnD36Mfew-pWKgRYE3pgV4AYEKpCR_hbY',
    appId: '1:805932440174:ios:a7dce38fbb5ed8f4f6e47f',
    messagingSenderId: '805932440174',
    projectId: 'inpatient-transport',
    storageBucket: 'inpatient-transport.firebasestorage.app',
    iosBundleId: 'com.example.inpatientTransport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnD36Mfew-pWKgRYE3pgV4AYEKpCR_hbY',
    appId: '1:805932440174:ios:a7dce38fbb5ed8f4f6e47f',
    messagingSenderId: '805932440174',
    projectId: 'inpatient-transport',
    storageBucket: 'inpatient-transport.firebasestorage.app',
    iosBundleId: 'com.example.inpatientTransport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrEyepVi0ocK769ME74RNbBvVys-RITkk',
    appId: '1:805932440174:web:123fc01f79865fe4f6e47f',
    messagingSenderId: '805932440174',
    projectId: 'inpatient-transport',
    authDomain: 'inpatient-transport.firebaseapp.com',
    storageBucket: 'inpatient-transport.firebasestorage.app',
  );
}
